language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended lmodern

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # Install Python and required packages.
  - conda install -c conda-forge mamba
  - mamba env create -f environment.yml
  - source activate jax-unirep
  - python setup.py install
  - pip install codecov
  # Ensure that the kernel is installed into the compute environment.
  - python -m ipykernel install --user --name jax-unirep
  # Ensure that jupyterlab's ipywidgets are displayed correctly.
  # This is important because we want progress bars to render correctly
  # in the mkdocs notebooks.
  - jupyter labextension install @jupyter-widgets/jupyterlab-manager

script:
  # Check formatting with black
  - make style
  # Run tests
  - make test
  # Build docs.
  # We want to build docs on every build,
  # because we want to guarantee that the notebooks run without error.
  # Hence, it is in the `script` section rather than `before_deploy` section.
  - mkdocs build

after_success:
  - codecov

before_deploy:
  # # Build paper
  # - make paper
  # - mkdir -p docs/
  # - cp -r paper/* docs/.
  # # Diagnostic commands
  # - ls docs/

  # Diagnostic command
  - ls site/

# This is an example to deploy to a branch through Travis.
deploy:
  provider: pages
  cleanup: false
  deploy_key: $GITHUB_TOKEN
  edge: true # opt in to dpl v2
  keep_history: false
  # We read the master branch
  on:
    branch: master
  # Take the docs/ directory
  local_dir: site
  # Publish to the gh-pages branch
  target_branch: gh-pages
  verbose: true
