name: jax-unirep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bumpversion
  - conda>=4.8.2
  - coverage>=6.3.2
  - hypothesis>=6.39.1
  - jax>=0.3.1
  - jaxlib>=0.3.0
  - jupyter
  - jupyterlab
  - multipledispatch>=0.6.0
  - numpy>=1.22.2
  - pyprojroot>=0.2.0
  - pytest>=7.0.1
  - pandoc>=2.17.1.1
  - pytest-cov>=3.0.0
  - pre-commit
  - ipykernel>=6.9.1
  - optuna>=2.10.0
  - scikit-learn>=1.0.2
  - twine
  - pip
  # mkdocs dependencies
  - click
  - regex
  - typed-ast
  # Code style
  - black>=22.1.0
  - isort>=5.10.1
  - pylint
  - pydocstyle
  # Other things
  - psutil
  - pip:
      - pandoc-fignos
      - pandoc-eqnos
      - pandoc-tablenos
      - pandoc-secnos
      - Pygments
      - mkdocs
      - mkdocs-material
      - mkautodoc
      - mknotebooks
